#!/usr/bin/env bash
#
# bootstrap installs things.

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

echo ''

info() {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user() {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success() {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail() {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

setup_gitconfig() {
info 'setup gitconfig'
  # if there is no user.email, we'll assume it's a new machine/setup and ask it
  if [ -z "$(git config --global --get user.email)" ]; then
    user ' - What is your github author name?'
    read -r user_name
    user ' - What is your github author email?'
    read -r user_email

    git config --global user.name "$user_name"
    git config --global user.email "$user_email"
  else
    # otherwise this gitconfig was already made
    info "already configured"
  fi
  # include the gitconfig.local file
  git config --global include.path ~/.gitconfig.local
  success 'gitconfig'
}


link_file() {
  if [ -e "$2" ]; then
    if [ "$(readlink "$2")" = "$1" ]; then
      success "skipped $1"
      return 0
    else
      mv "$2" "$2.backup"
      success "moved $2 to $2.backup"
    fi
  fi
  ln -sf "$1" "$2"
  success "linked $1 to $2"
}

install_dotfiles() {
  info 'installing dotfiles'
  find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*' |
    while read -r src; do
      dst="$HOME/.$(basename "${src%.*}")"
      link_file "$src" "$dst"
    done
}

osx_defaults() {
  info 'setting osx defaults'
  if source macos/osxdefaults | while read -r data; do info "$data"; done
  then
    success 'osx defaults'
  else
    fail 'error installing dependencies'
  fi
}

install_dependencies() {
  info 'installing dependencies'
  if source bin/dot | while read -r data; do info "$data"; done
  then
    success 'dependencies installed'
  else
    fail 'error installing dependencies'
  fi
}

find_zsh() {
  if which zsh >/dev/null 2>&1 && grep "$(which zsh)" /etc/shells >/dev/null; then
    which zsh
  else
    echo "/bin/zsh"
  fi
}

set_zsh_default_shell() {
  zsh="$(find_zsh)"
  which chsh >/dev/null 2>&1 &&
    chsh -s "$zsh" &&
    success "set $("$zsh" --version) at $zsh as default shell"
}

install_ohmyzsh() {
  info 'installing oh-my-zsh'
  sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  success 'Oh My ZSH!'
}

setup_gitconfig
install_dotfiles
osx_defaults
install_dependencies
set_zsh_default_shell
install_ohmyzsh

echo ''
echo '  All installed!'
