#!/usr/bin/env bash
#
# Run all dotfiles installers.

DOTFILES_ROOT=$(pwd -P)

set -e

source script/log

# Install homebrew if needed
$DOTFILES_ROOT/homebrew/install.sh

# Run Homebrew through the Brewfile
brew bundle -v
brew cask cleanup

# Agreeing to the Xcode/iOS license
sudo xcodebuild -license accept

# CocoaPods manages library dependencies for Xcode projects
info "Installing Cocoapods"
sudo gem install cocoapods

# find the installers and run them iteratively
info "Find and executes install scripts"
find . -name install.sh | while read installer ; do 
	info "${installer}..."
	sh -c "${installer}" ;
done

# Update Dock
info "Updating Dock apps"
source $DOTFILES_ROOT/macos/update_dock.sh