#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

source script/log

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
info "› brew bundle"
brew bundle -v
brew cask cleanup

info "› Installing software from Mac App Store"
sh macappstore

# find the installers and run them iteratively
info "› Find and executes install scripts"
find . -name install.sh | while read installer ; do 
	info "›› ${installer}..."
	sh -c "${installer}" ;
done
